### PR TITLE
add StarkGate STRK bridge contract

### PR DESCRIPTION
**Pull request by adrienlacombe**

### CODE REVIEW

**Comment by adrienlacombe** [comment]
I guess you would need to add it @jnicoulaud-ledger :)

https://github.com/LedgerHQ/clear-signing-erc7730-registry/actions/runs/11705498643/job/32601397534?pr=76#step:7:13

**Comment by jnicoulaud-ledger** [comment]
Ha, we need signed commits :pray:

**Comment by adrienlacombe** [comment]
> Ha, we need signed commits 🙏

oh let me see

**Comment by adrienlacombe** [comment]
> @adrienlacombe this is due to pull requests from forks unable to access repository secrets, we have yet to implement a solution for this :loading:
> 
> but your descriptor is valid: image
> 
> (the linter can be run locally, see [here](https://ledgerhq.github.io/python-erc7730/pages/usage_cli.html))
> 
> Also, note the implementation is not yet available, but it should be before end of year ;)

thank you

**Comment by adrienlacombe** [comment]
commit signed @jnicoulaud-ledger

**Pull request merged**
